services:
  backend:
    image: ghcr.io/egemenyildiz3/noter-backend:latest
    container_name: noter-backend
    volumes:
      - noter-data:/data
    expose:
      - "8080"
    ports:
      - "5199:8080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/egemenyildiz3/noter-frontend:latest
    container_name: noter-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  noter-data:
