services:
  backend:
    build:
      context: ./backend/Noter.Api
    container_name: noter-backend
    env_file:
      - .env
    environment:
      - EXTRA_BACKUP_PATH=${EXTRA_BACKUP_PATH:-/home/egemen/file-storage/information}
    volumes:
      - noter-data:/data
      - ${EXTRA_BACKUP_PATH:-/home/egemen/file-storage/information}:${EXTRA_BACKUP_PATH:-/home/egemen/file-storage/information}
    expose:
      - "8080"
    ports:
      - "5199:8080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/egemenyildiz3/noter-frontend:latest
    container_name: noter-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  noter-data:
